Default: &defaults
  user: yesod
  password: yesod
  host: localhost
  port: 5432
  database: yesod-blog
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: blog_test
  <<: *defaults

Staging:
  database: blog_staging
  poolsize: 100
  <<: *defaults

Production:
  database: blog_production
  poolsize: 100
  <<: *defaults
